From redis/redis-stack-server:latest

#redis-stack vs redis-stack-server image
 #redis-stack : contains both Redis Stack server and RedisInsight. This container is best for local development because you can use RedisInsight to visualize your data.
 #redis-stack-server : provides Redis Stack but excludes RedisInsight. This container is best for production deployment.

